[metadata]
version = "1.0"

[versions]
# Kyori
indra = "3.1.3"

[libraries]

# File reading/writing
gson = "com.google.code.gson:gson:2.10.1"

# Build
build-indra-common = { module = "net.kyori:indra-common", version.ref = "indra" }
build-indra-publishing = { module = "net.kyori:indra-publishing-gradle-plugin", version.ref = "indra" }
build-blossom = "net.kyori:blossom:1.3.1"
build-testLogger = "com.adarshr:gradle-test-logger-plugin:4.0.0"
build-errorpronePlugin = "net.ltgt.gradle:gradle-errorprone-plugin:2.0.2"

# Miscellaneous
annotations = "org.jetbrains:annotations:24.0.1"

[plugins]
indra-sonatype = { id = "net.kyori.indra.publishing.sonatype", version.ref = "indra" }